name: latitude-llm
windows:
  - workspace: cd .
  - apps: pnpm dev --filter='./apps/*'
  - packages: pnpm dev --filter='./packages/*'
  - docker: docker compose up --menu=false
  - studio: cd packages/core && pnpm db:studio
